options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Ambil kredensial dari Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ambil kredensial untuk akses Google Cloud Storage
        gcloud secrets versions access latest --secret=GOOGLE_APPLICATION_CREDENTIALS > /workspace/destinasyik-API.json

  # Step 2: Build Docker Image untuk aplikasi Express
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '.'

  # Step 3: Push Docker Image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'

  # Step 4: Deploy aplikasi ke Cloud Run dengan environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/$PROJECT_ID/destinasyikapi',
      '--region', 'asia-southeast2',  
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 
      'GCS_BUCKET_NAME=destinasyikfile,GOOGLE_APPLICATION_CREDENTIALS=/app/destinasyik-API.json',  
      '--timeout', '300s'
    ]

#service
substitutions:
  _SERVICE_NAME: 'destinasyikapi-service'
  _IMAGE_NAME: 'destinasyikapi'