# Jika Anda di direktori repository
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/destinasyik', '.']
images: ['gcr.io/destinasyik/destinasyikreccomenders']" > cloudbuild.yaml