options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Akses Service Key dari Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=GOOGLE_APPLICATION_CREDENTIALS > /app/destinasyik-API.json

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '.'

  # Step 3: Push Docker image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'

  # Step 4: Jalankan migrasi database
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_USERNAME=$(gcloud secrets versions access latest --secret=DB_USERNAME)
        DB_PASSWORD=$(gcloud secrets versions access latest --secret=DB_PASSWORD)
        DB_HOST=$(gcloud secrets versions access latest --secret=DB_HOST)
        DB_NAME=$(gcloud secrets versions access latest --secret=DB_NAME)
        DB_PORT=$(gcloud secrets versions access latest --secret=DB_PORT)

        docker run \
          --rm \
          -e DB_USERNAME="$DB_USERNAME" \
          -e DB_PASSWORD="$DB_PASSWORD" \
          -e DB_HOST="$DB_HOST" \
          -e DB_NAME="$DB_NAME" \
          -e DB_PORT="$DB_PORT" \
          gcr.io/$PROJECT_ID/destinasyikapi \
          npm run migrate:production