options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Akses Service Key dan DB Secrets dari Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Akses kredensial GCP (Google Application Credentials)
        gcloud secrets versions access latest --secret=GOOGLE_APPLICATION_CREDENTIALS > /app/destinasyik-API.json
        
        # Akses variabel environment untuk database dan simpan ke file
        export DB_USERNAME=$(gcloud secrets versions access latest --secret=DB_USERNAME)
        export DB_PASSWORD=$(gcloud secrets versions access latest --secret=DB_PASSWORD)
        export DB_HOST=$(gcloud secrets versions access latest --secret=DB_HOST)
        export DB_NAME=$(gcloud secrets versions access latest --secret=DB_NAME)
        export DB_PORT=$(gcloud secrets versions access latest --secret=DB_PORT)
        
        # Tulis variabel ini ke file agar dapat diakses di langkah berikutnya
        echo "DB_USERNAME=${DB_USERNAME}" > /app/db-env.txt
        echo "DB_PASSWORD=${DB_PASSWORD}" >> /app/db-env.txt
        echo "DB_HOST=${DB_HOST}" >> /app/db-env.txt
        echo "DB_NAME=${DB_NAME}" >> /app/db-env.txt
        echo "DB_PORT=${DB_PORT}" >> /app/db-env.txt

  # Step 2: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '.'

  # Step 3: Push Docker Image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'

  # Step 4: Jalankan Migrasi Database
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ambil dan export variabel environment yang diperlukan untuk migrasi
        source /app/db-env.txt
        
        docker run \
          --rm \
          -e DB_USERNAME="$DB_USERNAME" \
          -e DB_PASSWORD="$DB_PASSWORD" \
          -e DB_HOST="$DB_HOST" \
          -e DB_NAME="$DB_NAME" \
          -e DB_PORT="$DB_PORT" \
          gcr.io/$PROJECT_ID/destinasyikapi \
          npm run migrate:production

  # Step 5: Deploy ke Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ambil variabel tambahan dari Secret Manager dan export
        NODE_ENV=$(gcloud secrets versions access latest --secret=NODE_ENV)
        SECRET_KEY=$(gcloud secrets versions access latest --secret=SECRET_KEY)
        PORT=$(gcloud secrets versions access latest --secret=PORT)
        MODEL_BASE_URL=$(gcloud secrets versions access latest --secret=MODEL_BASE_URL)
        GOOGLE_APPLICATION_CREDENTIALS=/app/destinasyik-API.json
        GCS_BUCKET_NAME=destinasyikfile

        # Ambil variabel environment untuk database
        source /app/db-env.txt
        
        # Deploy Cloud Run service dengan environment variables
        gcloud run deploy destinasyikreccomenders-service \
          --image gcr.io/$PROJECT_ID/destinasyikapi \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --timeout=600 \
          --set-env-vars \
          DB_USERNAME="$DB_USERNAME",DB_PASSWORD="$DB_PASSWORD",DB_HOST="$DB_HOST",DB_NAME="$DB_NAME",DB_PORT="$DB_PORT",NODE_ENV="$NODE_ENV",SECRET_KEY="$SECRET_KEY",PORT="$PORT",MODEL_BASE_URL="$MODEL_BASE_URL",GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS",GCS_BUCKET_NAME="$GCS_BUCKET_NAME"