# Jika Anda di direktori repository
echo "steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/\$PROJECT_ID/destinasyik', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/\$PROJECT_ID/destinasyik']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'destinasyik', '--image', 'gcr.io/\$PROJECT_ID/destinasyik', '--region', 'asia-southeast2', '--platform', 'managed']
images: ['gcr.io/\$PROJECT_ID/destinasyik']" > cloudbuild.yaml