options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Access Service Key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=GOOGLE_APPLICATION_CREDENTIALS > /app/destinasyik-API.json

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '.'

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'

  # Step 4: Database Migration
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run \
          --rm \
          -e DB_USERNAME="$(gcloud secrets versions access latest --secret=DB_USERNAME)" \
          -e DB_PASSWORD="$(gcloud secrets versions access latest --secret=DB_PASSWORD)" \
          -e DB_HOST="$(gcloud secrets versions access latest --secret=DB_HOST)" \
          -e DB_NAME="$(gcloud secrets versions access latest --secret=DB_NAME)" \
          -e DB_PORT="$(gcloud secrets versions access latest --secret=DB_PORT)" \
          gcr.io/$PROJECT_ID/destinasyikapi \
          npm run migrate:production

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy destinasyikreccomenders-service \
          --image gcr.io/$PROJECT_ID/destinasyikapi \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --timeout=600 \
          --set-env-vars \
          DB_USERNAME="$(gcloud secrets versions access latest --secret=DB_USERNAME)",\
          DB_PASSWORD="$(gcloud secrets versions access latest --secret=DB_PASSWORD)",\
          DB_HOST="$(gcloud secrets versions access latest --secret=DB_HOST)",\
          DB_NAME="$(gcloud secrets versions access latest --secret=DB_NAME)",\
          DB_PORT="$(gcloud secrets versions access latest --secret=DB_PORT)",\
          NODE_ENV="$(gcloud secrets versions access latest --secret=NODE_ENV)",\
          SECRET_KEY="$(gcloud secrets versions access latest --secret=SECRET_KEY)",\
          PORT="$(gcloud secrets versions access latest --secret=PORT)",\
          MODEL_BASE_URL="$(gcloud secrets versions access latest --secret=MODEL_BASE_URL)",\
          GOOGLE_APPLICATION_CREDENTIALS=/workspace/destinasyik-API.json,\
          GCS_BUCKET_NAME=destinasyikfile