options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Akses Service Key dari Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ambil service key dari Secret Manager
        gcloud secrets versions access latest --secret=GOOGLE_APPLICATION_CREDENTIALS > /workspace/destinasyik-API.json

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '.'

  # Step 3: Push Docker image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'

  # Step 4: Menjalankan migrasi database
  - name: 'gcr.io/cloud-builders/docker'  # Perbaiki image builder menjadi 'docker'
    args:
      - 'run'
      - '--rm'
      - '-e'
      - 'DB_USERNAME=$(gcloud secrets versions access latest --secret=DB_USERNAME)'
      - '-e'
      - 'DB_PASSWORD=$(gcloud secrets versions access latest --secret=DB_PASSWORD)'
      - '-e'
      - 'DB_HOST=$(gcloud secrets versions access latest --secret=DB_HOST)'
      - '-e'
      - 'DB_NAME=$(gcloud secrets versions access latest --secret=DB_NAME)'
      - '-e'
      - 'DB_PORT=$(gcloud secrets versions access latest --secret=DB_PORT)'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'  # Perbaiki nama image
      - 'sequelize'
      - 'db:migrate'

  # Step 5: Deploy ke Cloud Run setelah migrasi berhasil
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_USERNAME=$(gcloud secrets versions access latest --secret=DB_USERNAME)'
      - 'DB_PASSWORD=$(gcloud secrets versions access latest --secret=DB_PASSWORD)'
      - 'DB_HOST=$(gcloud secrets versions access latest --secret=DB_HOST)'
      - 'DB_NAME=$(gcloud secrets versions access latest --secret=DB_NAME)'
      - 'DB_PORT=$(gcloud secrets versions access latest --secret=DB_PORT)'
      - 'NODE_ENV=$(gcloud secrets versions access latest --secret=NODE_ENV)'
      - 'SECRET_KEY=$(gcloud secrets versions access latest --secret=SECRET_KEY)'
      - 'PORT=$(gcloud secrets versions access latest --secret=PORT)'
      - 'MODEL_BASE_URL=$(gcloud secrets versions access latest --secret=MODEL_BASE_URL)'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/app/destinasyik-API.json'
      - 'GCS_BUCKET_NAME=destinasyikfile'

substitutions:
  _SERVICE_NAME: 'destinasyikapi-service'