options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Ambil kredensial aplikasi dari Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ambil kredensial untuk akses Google Cloud Storage
        gcloud secrets versions access latest --secret=GOOGLE_APPLICATION_CREDENTIALS > /workspace/destinasyik-API.json

  # Step 2: Build Docker Image untuk aplikasi Express
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'
      - '.'

  # Step 3: Push Docker Image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikapi'

  # Step 4: Akses Cloud Storage (Bucket) untuk memungkinkan upload gambar
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        STORAGE_BUCKET_NAME="destinasyikfile"
        gcloud auth activate-service-account --key-file /workspace/destinasyik-API.json
        
        gcloud storage buckets list --filter="name:$STORAGE_BUCKET_NAME"

  # Step 5: Deploy aplikasi ke Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_USERNAME=$(gcloud secrets versions access latest --secret=DB_USERNAME)
        DB_PASSWORD=$(gcloud secrets versions access latest --secret=DB_PASSWORD)
        DB_HOST=$(gcloud secrets versions access latest --secret=DB_HOST)
        DB_NAME=$(gcloud secrets versions access latest --secret=DB_NAME)
        DB_PORT=$(gcloud secrets versions access latest --secret=DB_PORT)
        NODE_ENV=$(gcloud secrets versions access latest --secret=NODE_ENV)
        SECRET_KEY=$(gcloud secrets versions access latest --secret=SECRET_KEY)
        PORT=$(gcloud secrets versions access latest --secret=PORT)
        GOOGLE_APPLICATION_CREDENTIALS=/workspace/destinasyik-API.json
        GCS_BUCKET_NAME="destinasyikfile"

        # Deploy ke Cloud Run
        gcloud run deploy destinasyikreccomenders-service \
          --image gcr.io/$PROJECT_ID/destinasyikapi \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --timeout=600 \
          --set-env-vars \
          DB_USERNAME="$DB_USERNAME",DB_PASSWORD="$DB_PASSWORD",DB_HOST="$DB_HOST",DB_NAME="$DB_NAME",DB_PORT="$DB_PORT",NODE_ENV="$NODE_ENV",SECRET_KEY="$SECRET_KEY",PORT="$PORT",GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS",GCS_BUCKET_NAME="$GCS_BUCKET_NAME"